#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer	true

bspc config border_width			2
bspc config border_radius			7
bspc config focused_border_color 	"#b491c9"
bspc config window_gap			5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

